<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('movies')->truncate();

        $movies = 
        [
            [
                'title' => 'The Shawshank Redemption',
                'slug' => Str::slug('The Shawshank Redemption'),
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'director' => 'Frank Darabont',
                'writers' => 'Stephen King (short story "Rita Hayworth and Shawshank Redemption"), Frank Darabont (screenplay)',
                'stars' => 'Tim Robbins, Morgan Freeman, Bob Gunton',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1994-09-23',
                'duration' => 142,
                'url_720' => 'https://www.youtube.com/embed/6hB3S9bIaco',
                'url_1080' => 'https://www.youtube.com/embed/PLl99DlL6b4',
                'url_4k' => 'https://www.youtube.com/embed/NmzuHjWmXOc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Godfather',
                'slug' => Str::slug('The Godfather'),
                'description' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
                'director' => 'Francis Ford Coppola',
                'writers' => 'Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by)',
                'stars' => 'Marlon Brando, Al Pacino, James Caan',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1972-03-24',
                'duration' => 175,
                'url_720' => 'https://www.youtube.com/embed/sY1S34973zA',
                'url_1080' => 'https://www.youtube.com/embed/UaVTIH8mujA',
                'url_4k' => 'https://www.youtube.com/embed/1x0GpEZnwa8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Dark Knight',
                'slug' => Str::slug('The Dark Knight'),
                'description' => 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay)',
                'stars' => 'Christian Bale, Heath Ledger, Aaron Eckhart',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2008-07-18',
                'duration' => 152,
                'url_720' => 'https://www.youtube.com/embed/EXeTwQWrcwY',
                'url_1080' => 'https://www.youtube.com/embed/LDG9bisJEaI',
                'url_4k' => 'https://www.youtube.com/embed/8gqM4BCgG8Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blade Runner 2049',
                'slug' => Str::slug('Blade Runner 2049'),
                'description' => 'A young blade runner\'s discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who\'s been missing for thirty years.',
                'director' => 'Denis Villeneuve',
                'writers' => 'Hampton Fancher (screenplay), Michael Green (screenplay)',
                'stars' => 'Ryan Gosling, Harrison Ford, Ana de Armas',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2017-10-06',
                'duration' => 164,
                'url_720' => 'https://www.youtube.com/embed/gCcx85zbxz4',
                'url_1080' => 'https://www.youtube.com/embed/dZOaI_Fn5o4',
                'url_4k' => 'https://www.youtube.com/embed/8ixEWrTLiQ4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Forrest Gump',
                'slug' => Str::slug('Forrest Gump'),
                'description' => 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
                'director' => 'Robert Zemeckis',
                'writers' => 'Winston Groom (novel), Eric Roth (screenplay)',
                'stars' => 'Tom Hanks, Robin Wright, Gary Sinise',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1994-07-06',
                'duration' => 142,
                'url_720' => 'https://www.youtube.com/embed/bLvqoHBptjg',
                'url_1080' => 'https://www.youtube.com/embed/uPIEn0M8su0',
                'url_4k' => 'https://www.youtube.com/embed/XHhAG-YLdk8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inception',
                'slug' => Str::slug('Inception'),
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'director' => 'Christopher Nolan',
                'writers' => 'Christopher Nolan',
                'stars' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2010-07-16',
                'duration' => 148,
                'url_720' => 'https://www.youtube.com/embed/YoHD9XEInc0',
                'url_1080' => 'https://www.youtube.com/embed/8hP9D6kZseM',
                'url_4k' => 'https://www.youtube.com/embed/HcoZbHBDHQA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fight Club',
                'slug' => Str::slug('Fight Club'),
                'description' => 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
                'director' => 'David Fincher',
                'writers' => 'Chuck Palahniuk (novel), Jim Uhls (screenplay)',
                'stars' => 'Brad Pitt, Edward Norton, Helena Bonham Carter',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1999-10-15',
                'duration' => 139,
                'url_720' => 'https://www.youtube.com/embed/qtRKdVHc-cE',
                'url_1080' => 'https://www.youtube.com/embed/BdJKm16Co6M',
                'url_4k' => 'https://www.youtube.com/embed/O1nDozs-LxI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Matrix',
                'slug' => Str::slug('The Matrix'),
                'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
                'director' => 'Lana Wachowski, Lilly Wachowski',
                'writers' => 'Lana Wachowski, Lilly Wachowski',
                'stars' => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1999-03-31',
                'duration' => 136,
                'url_720' => 'https://www.youtube.com/embed/vKQi3bBA1y8',
                'url_1080' => 'https://www.youtube.com/embed/m8e-FF8MsqU',
                'url_4k' => 'https://www.youtube.com/embed/9ix7TUGVYIo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Goodfellas',
                'slug' => Str::slug('Goodfellas'),
                'description' => 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
                'director' => 'Martin Scorsese',
                'writers' => 'Nicholas Pileggi (book), Martin Scorsese (screenplay)',
                'stars' => 'Robert De Niro, Ray Liotta, Joe Pesci',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1990-09-19',
                'duration' => 146,
                'url_720' => 'https://www.youtube.com/embed/2ilzidi_J8Q',
                'url_1080' => 'https://www.youtube.com/embed/qo5jJpHtI1Y',
                'url_4k' => 'https://www.youtube.com/embed/WHXxVmeGQUc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Silence of the Lambs',
                'slug' => Str::slug('The Silence of the Lambs'),
                'description' => 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
                'director' => 'Jonathan Demme',
                'writers' => 'Thomas Harris (novel), Ted Tally (screenplay)',
                'stars' => 'Jodie Foster, Anthony Hopkins, Scott Glenn',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1991-02-14',
                'duration' => 118,
                'url_720' => 'https://www.youtube.com/embed/W6Mm8Sbe__o',
                'url_1080' => 'https://www.youtube.com/embed/RuX2MQeb8UM',
                'url_4k' => 'https://www.youtube.com/embed/8Qsq6DrYDxE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Interstellar',
                'slug' => Str::slug('Interstellar'),
                'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan, Christopher Nolan',
                'stars' => 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2014-11-07',
                'duration' => 169,
                'url_720' => 'https://www.youtube.com/embed/zSWdZVtXT7E',
                'url_1080' => 'https://www.youtube.com/embed/0vxOhd4qlnA',
                'url_4k' => 'https://www.youtube.com/embed/2LqzF5WauAw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lord of the Rings: The Fellowship of the Ring',
                'slug' => Str::slug('The Lord of the Rings: The Fellowship of the Ring'),
                'description' => 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
                'director' => 'Peter Jackson',
                'writers' => 'J.R.R. Tolkien (novel), Fran Walsh (screenplay)',
                'stars' => 'Elijah Wood, Ian McKellen, Viggo Mortensen',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2001-12-19',
                'duration' => 178,
                'url_720' => 'https://www.youtube.com/embed/V75dMMIW2B4',
                'url_1080' => 'https://www.youtube.com/embed/_e8QGuG50ro',
                'url_4k' => 'https://www.youtube.com/embed/uYnQDsaxHZU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Parasite',
                'slug' => Str::slug('Parasite'),
                'description' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
                'director' => 'Bong Joon Ho',
                'writers' => 'Bong Joon Ho (story), Han Jin Won (screenplay)',
                'stars' => 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2019-05-21',
                'duration' => 132,
                'url_720' => 'https://www.youtube.com/embed/SEUXfv87Wpk',
                'url_1080' => 'https://www.youtube.com/embed/5xH0HfJHsaY',
                'url_4k' => 'https://www.youtube.com/embed/PhPROeYAYBA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Whiplash',
                'slug' => Str::slug('Whiplash'),
                'description' => 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
                'director' => 'Damien Chazelle',
                'writers' => 'Damien Chazelle',
                'stars' => 'Miles Teller, J.K. Simmons, Melissa Benoist',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2014-10-10',
                'duration' => 106,
                'url_720' => 'https://www.youtube.com/embed/7d_jQycdQGo',
                'url_1080' => 'https://www.youtube.com/embed/ZZY-Ytrw2co',
                'url_4k' => 'https://www.youtube.com/embed/teHfyby_veU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Green Mile',
                'slug' => Str::slug('The Green Mile'),
                'description' => 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
                'director' => 'Frank Darabont',
                'writers' => 'Stephen King (novel), Frank Darabont (screenplay)',
                'stars' => 'Tom Hanks, Michael Clarke Duncan, David Morse',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1999-12-10',
                'duration' => 189,
                'url_720' => 'https://www.youtube.com/embed/Ki4haFrqSrw',
                'url_1080' => 'https://www.youtube.com/embed/Bg7epsq0OIQ',
                'url_4k' => 'https://www.youtube.com/embed/ctRK-4Vt7dA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Departed',
                'slug' => Str::slug('The Departed'),
                'description' => 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
                'director' => 'Martin Scorsese',
                'writers' => 'Alan Mak (film), Felix Chong (film)',
                'stars' => 'Leonardo DiCaprio, Matt Damon, Jack Nicholson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2006-10-06',
                'duration' => 151,
                'url_720' => 'https://www.youtube.com/embed/iojhqm0JTW4',
                'url_1080' => 'https://www.youtube.com/embed/auYbpnEwBBg',
                'url_4k' => 'https://www.youtube.com/embed/SGWvwjZ0eDc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gladiator',
                'slug' => Str::slug('Gladiator'),
                'description' => 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
                'director' => 'Ridley Scott',
                'writers' => 'David Franzoni (story), John Logan (screenplay)',
                'stars' => 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2000-05-05',
                'duration' => 155,
                'url_720' => 'https://www.youtube.com/embed/owK1qxDselE',
                'url_1080' => 'https://www.youtube.com/embed/P5ieIbInFpg',
                'url_4k' => 'https://www.youtube.com/embed/b_VKnQfZX4c',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Prestige',
                'slug' => Str::slug('The Prestige'),
                'description' => 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay)',
                'stars' => 'Christian Bale, Hugh Jackman, Scarlett Johansson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2006-10-20',
                'duration' => 130,
                'url_720' => 'https://www.youtube.com/embed/o4gHCmTQDVI',
                'url_1080' => 'https://www.youtube.com/embed/RLtaA9fFNXU',
                'url_4k' => 'https://www.youtube.com/embed/ijXruSzfGEc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Django Unchained',
                'slug' => Str::slug('Django Unchained'),
                'description' => 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
                'director' => 'Quentin Tarantino',
                'writers' => 'Quentin Tarantino',
                'stars' => 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2012-12-25',
                'duration' => 165,
                'url_720' => 'https://www.youtube.com/embed/0fUCuvNlOCg',
                'url_1080' => 'https://www.youtube.com/embed/_iH0UBYDI4g',
                'url_4k' => 'https://www.youtube.com/embed/eUdM9vrCbow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Social Network',
                'slug' => Str::slug('The Social Network'),
                'description' => 'As Harvard student Mark Zuckerberg creates the social networking site that would become Facebook, he is sued by the twins who claimed he stole their idea.',
                'director' => 'David Fincher',
                'writers' => 'Aaron Sorkin (screenplay), Ben Mezrich (book)',
                'stars' => 'Jesse Eisenberg, Andrew Garfield, Justin Timberlake',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2010-10-01',
                'duration' => 120,
                'url_720' => 'https://www.youtube.com/embed/lB95KLmpLR4',
                'url_1080' => 'https://www.youtube.com/embed/8N4TMvz6XwQ',
                'url_4k' => 'https://www.youtube.com/embed/2RB3edZyeYw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inglourious Basterds',
                'slug' => Str::slug('Inglourious Basterds'),
                'description' => 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theater owner\'s vengeful plans.',
                'director' => 'Quentin Tarantino',
                'writers' => 'Quentin Tarantino',
                'stars' => 'Brad Pitt, Christoph Waltz, Mélanie Laurent',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2009-08-21',
                'duration' => 153,
                'url_720' => 'https://www.youtube.com/embed/KnrRy6kSFF0',
                'url_1080' => 'https://www.youtube.com/embed/qRYgNqnqBdY',
                'url_4k' => 'https://www.youtube.com/embed/6AtLlVNsuAc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Grand Budapest Hotel',
                'slug' => Str::slug('The Grand Budapest Hotel'),
                'description' => 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
                'director' => 'Wes Anderson',
                'writers' => 'Wes Anderson (screenplay), Hugo Guinness (story)',
                'stars' => 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2014-03-28',
                'duration' => 99,
                'url_720' => 'https://www.youtube.com/embed/1Fg5iWmQjwk',
                'url_1080' => 'https://www.youtube.com/embed/zru-1DbbcsA',
                'url_4k' => 'https://www.youtube.com/embed/eTdf-nHhPWM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'La La Land',
                'slug' => Str::slug('La La Land'),
                'description' => 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
                'director' => 'Damien Chazelle',
                'writers' => 'Damien Chazelle',
                'stars' => 'Ryan Gosling, Emma Stone, John Legend',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2016-12-09',
                'duration' => 128,
                'url_720' => 'https://www.youtube.com/embed/0pdqf4P9MB8',
                'url_1080' => 'https://www.youtube.com/embed/45TbOYFZ0Lk',
                'url_4k' => 'https://www.youtube.com/embed/je0aAf2f8XQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mad Max: Fury Road',
                'slug' => Str::slug('Mad Max: Fury Road'),
                'description' => 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
                'director' => 'George Miller',
                'writers' => 'George Miller, Brendan McCarthy',
                'stars' => 'Tom Hardy, Charlize Theron, Nicholas Hoult',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2015-05-15',
                'duration' => 120,
                'url_720' => 'https://www.youtube.com/embed/hEJnMQG9ev8',
                'url_1080' => 'https://www.youtube.com/embed/YWNWi-ZWL3c',
                'url_4k' => 'https://www.youtube.com/embed/cdLl1GVjOrc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Shining',
                'slug' => Str::slug('The Shining'),
                'description' => 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.',
                'director' => 'Stanley Kubrick',
                'writers' => 'Stephen King (novel), Stanley Kubrick (screenplay)',
                'stars' => 'Jack Nicholson, Shelley Duvall, Danny Lloyd',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1980-05-23',
                'duration' => 146,
                'url_720' => 'https://www.youtube.com/embed/S014oGZiSdI',
                'url_1080' => 'https://www.youtube.com/embed/5Cb3ik6zP2I',
                'url_4k' => 'https://www.youtube.com/embed/FZQvIJxG9Xs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Se7en',
                'slug' => Str::slug('Se7en'),
                'description' => 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
                'director' => 'David Fincher',
                'writers' => 'Andrew Kevin Walker',
                'stars' => 'Morgan Freeman, Brad Pitt, Kevin Spacey',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1995-09-22',
                'duration' => 127,
                'url_720' => 'https://www.youtube.com/embed/znmZoVkCjpI',
                'url_1080' => 'https://www.youtube.com/embed/SpKbZ_3zlb0',
                'url_4k' => 'https://www.youtube.com/embed/J4YV2_TcCoE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lion King',
                'slug' => Str::slug('The Lion King'),
                'description' => 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
                'director' => 'Roger Allers, Rob Minkoff',
                'writers' => 'Irene Mecchi (screenplay), Jonathan Roberts (screenplay)',
                'stars' => 'Matthew Broderick, Jeremy Irons, James Earl Jones',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1994-06-24',
                'duration' => 88,
                'url_720' => 'https://www.youtube.com/embed/4sj1MT05lAA',
                'url_1080' => 'https://www.youtube.com/embed/eHcZlPpNt0Q',
                'url_4k' => 'https://www.youtube.com/embed/GibiNy4d4gc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Back to the Future',
                'slug' => Str::slug('Back to the Future'),
                'description' => 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.',
                'director' => 'Robert Zemeckis',
                'writers' => 'Robert Zemeckis, Bob Gale',
                'stars' => 'Michael J. Fox, Christopher Lloyd, Lea Thompson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1985-07-03',
                'duration' => 116,
                'url_720' => 'https://www.youtube.com/embed/qvsgGtivCgs',
                'url_1080' => 'https://www.youtube.com/embed/yosuvf7Unmg',
                'url_4k' => 'https://www.youtube.com/embed/7D7xWXEnW-4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Alien',
                'slug' => Str::slug('Alien'),
                'description' => 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.',
                'director' => 'Ridley Scott',
                'writers' => 'Dan O\'Bannon (screenplay), Ronald Shusett (story)',
                'stars' => 'Sigourney Weaver, Tom Skerritt, John Hurt',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1979-06-22',
                'duration' => 117,
                'url_720' => 'https://www.youtube.com/embed/LjLamj-b0I8',
                'url_1080' => 'https://www.youtube.com/embed/3mKPrxjwF7A',
                'url_4k' => 'https://www.youtube.com/embed/7bhWjnJgX8E',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Joker',
                'slug' => Str::slug('Joker'),
                'description' => 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
                'director' => 'Todd Phillips',
                'writers' => 'Todd Phillips (screenplay), Scott Silver (screenplay)',
                'stars' => 'Joaquin Phoenix, Robert De Niro, Zazie Beetz',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2019-10-04',
                'duration' => 122,
                'url_720' => 'https://www.youtube.com/embed/zAGVQLHvwOY',
                'url_1080' => 'https://www.youtube.com/embed/t433PEQGErc',
                'url_4k' => 'https://www.youtube.com/embed/rgXplohCw5o',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Terminator',
                'slug' => Str::slug('The Terminator'),
                'description' => 'A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity\'s future salvation.',
                'director' => 'James Cameron',
                'writers' => 'James Cameron, Gale Anne Hurd',
                'stars' => 'Arnold Schwarzenegger, Linda Hamilton, Michael Biehn',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1984-10-26',
                'duration' => 107,
                'url_720' => 'https://www.youtube.com/embed/k64P4l2Wmeg',
                'url_1080' => 'https://www.youtube.com/embed/c4Jo8QoOTQ4',
                'url_4k' => 'https://www.youtube.com/embed/7QXDPzx71jQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Avengers: Endgame',
                'slug' => Str::slug('Avengers: Endgame'),
                'description' => 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.',
                'director' => 'Anthony Russo, Joe Russo',
                'writers' => 'Christopher Markus (screenplay), Stephen McFeely (screenplay)',
                'stars' => 'Robert Downey Jr., Chris Evans, Mark Ruffalo',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2019-04-26',
                'duration' => 181,
                'url_720' => 'https://www.youtube.com/embed/TcMBFSGVi1c',
                'url_1080' => 'https://www.youtube.com/embed/hA6hldpSTF8',
                'url_4k' => 'https://www.youtube.com/embed/4jGRyEa2jhE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Spirited Away',
                'slug' => Str::slug('Spirited Away'),
                'description' => 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
                'director' => 'Hayao Miyazaki',
                'writers' => 'Hayao Miyazaki',
                'stars' => 'Rumi Hiiragi, Miyu Irino, Mari Natsuki',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2001-07-20',
                'duration' => 125,
                'url_720' => 'https://www.youtube.com/embed/ByXuk9QqQkk',
                'url_1080' => 'https://www.youtube.com/embed/39udgGPyYMg',
                'url_4k' => 'https://www.youtube.com/embed/1C3ujeG9E1U',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Pianist',
                'slug' => Str::slug('The Pianist'),
                'description' => 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.',
                'director' => 'Roman Polanski',
                'writers' => 'Ronald Harwood (screenplay), Władysław Szpilman (book)',
                'stars' => 'Adrien Brody, Thomas Kretschmann, Frank Finlay',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2002-09-25',
                'duration' => 150,
                'url_720' => 'https://www.youtube.com/embed/BFwGqLa_oAo',
                'url_1080' => 'https://www.youtube.com/embed/u_jE7-6Uv7E',
                'url_4k' => 'https://www.youtube.com/embed/3gMFCoggw6k',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Intouchables',
                'slug' => Str::slug('The Intouchables'),
                'description' => 'After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.',
                'director' => 'Olivier Nakache, Éric Toledano',
                'writers' => 'Olivier Nakache, Éric Toledano',
                'stars' => 'François Cluzet, Omar Sy, Anne Le Ny',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2011-11-02',
                'duration' => 112,
                'url_720' => 'https://www.youtube.com/embed/34WIbmXkewU',
                'url_1080' => 'https://www.youtube.com/embed/0RqDiYnFxTk',
                'url_4k' => 'https://www.youtube.com/embed/cXuH3xX1JN4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lives of Others',
                'slug' => Str::slug('The Lives of Others'),
                'description' => 'In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives.',
                'director' => 'Florian Henckel von Donnersmarck',
                'writers' => 'Florian Henckel von Donnersmarck',
                'stars' => 'Ulrich Mühe, Martina Gedeck, Sebastian Koch',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNmQyNmJjM2ItNTQzYi00ZjMxLWFjMDYtZjUyN2YwZDk5YWQ2XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2006-03-23',
                'duration' => 137,
                'url_720' => 'https://www.youtube.com/embed/n3_iLOp6IhM',
                'url_1080' => 'https://www.youtube.com/embed/FppW5ml4vdw',
                'url_4k' => 'https://www.youtube.com/embed/2kLtS2YaDmE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cinema Paradiso',
                'slug' => Str::slug('Cinema Paradiso'),
                'description' => 'A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the cinema\'s projectionist.',
                'director' => 'Giuseppe Tornatore',
                'writers' => 'Giuseppe Tornatore (story), Vanna Paoli (collaboration)',
                'stars' => 'Philippe Noiret, Enzo Cannavale, Antonella Attili',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BM2FhYjEyYmYtMDI1Yy00YTdlLWI2NWQtYmEzNzAxOGY1NjY2XkEyXkFqcGdeQXVyNTA3NTIyNDg@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1988-11-17',
                'duration' => 155,
                'url_720' => 'https://www.youtube.com/embed/C2-GX0Tltgw',
                'url_1080' => 'https://www.youtube.com/embed/maV2JejHEuY',
                'url_4k' => 'https://www.youtube.com/embed/3R0K_2q5gSM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Amélie',
                'slug' => Str::slug('Amélie'),
                'description' => 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and along the way, discovers love.',
                'director' => 'Jean-Pierre Jeunet',
                'writers' => 'Guillaume Laurant (scenario), Jean-Pierre Jeunet (scenario)',
                'stars' => 'Audrey Tautou, Mathieu Kassovitz, Rufus',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNDg4NjM1YjMtYmNhZC00MjM0LWFiZmYtNGY1YjA3MzZmODc5XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2001-04-25',
                'duration' => 122,
                'url_720' => 'https://www.youtube.com/embed/HUECWi5pX7o',
                'url_1080' => 'https://www.youtube.com/embed/sECzJY07oK4',
                'url_4k' => 'https://www.youtube.com/embed/2UT5xaAfxWU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Requiem for a Dream',
                'slug' => Str::slug('Requiem for a Dream'),
                'description' => 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.',
                'director' => 'Darren Aronofsky',
                'writers' => 'Hubert Selby Jr. (book), Darren Aronofsky (screenplay)',
                'stars' => 'Ellen Burstyn, Jared Leto, Jennifer Connelly',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOTdiNzJlOWUtNWMwNS00NmFlLWI0YTEtZmI3YjIzZWUyY2Y3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2000-10-06',
                'duration' => 102,
                'url_720' => 'https://www.youtube.com/embed/jzk-lmU4KZ4',
                'url_1080' => 'https://www.youtube.com/embed/0nU7dC9bIDg',
                'url_4k' => 'https://www.youtube.com/embed/3A1UqXWfhbY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Eternal Sunshine of the Spotless Mind',
                'slug' => Str::slug('Eternal Sunshine of the Spotless Mind'),
                'description' => 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.',
                'director' => 'Michel Gondry',
                'writers' => 'Charlie Kaufman (story), Michel Gondry (story)',
                'stars' => 'Jim Carrey, Kate Winslet, Tom Wilkinson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2004-03-19',
                'duration' => 108,
                'url_720' => 'https://www.youtube.com/embed/07-QBnEkgXU',
                'url_1080' => 'https://www.youtube.com/embed/yE-f1alkq9I',
                'url_4k' => 'https://www.youtube.com/embed/1GiLxkDK8sI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Oldboy',
                'slug' => Str::slug('Oldboy'),
                'description' => 'After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.',
                'director' => 'Park Chan-wook',
                'writers' => 'Garon Tsuchiya (story), Nobuaki Minegishi (comic)',
                'stars' => 'Choi Min-sik, Yoo Ji-tae, Kang Hye-jeong',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2003-11-21',
                'duration' => 120,
                'url_720' => 'https://www.youtube.com/embed/2HkjrJ6IK5E',
                'url_1080' => 'https://www.youtube.com/embed/rmxL6Q8cPAU',
                'url_4k' => 'https://www.youtube.com/embed/3HxEX7nD7Bg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Hunt',
                'slug' => Str::slug('The Hunt'),
                'description' => 'A teacher lives a lonely life, all the while struggling over his son\'s custody. His life slowly gets better as he finds love and receives good news from his son, but his new luck is about to be brutally shattered by an innocent little lie.',
                'director' => 'Thomas Vinterberg',
                'writers' => 'Tobias Lindholm (screenplay), Thomas Vinterberg (screenplay)',
                'stars' => 'Mads Mikkelsen, Thomas Bo Larsen, Annika Wedderkopp',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTg2NDg3ODg4NF5BMl5BanBnXkFtZTcwNzk3NTc3Nw@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2012-10-24',
                'duration' => 115,
                'url_720' => 'https://www.youtube.com/embed/Q6FuxsovV7s',
                'url_1080' => 'https://www.youtube.com/embed/dttG6nbBqkM',
                'url_4k' => 'https://www.youtube.com/embed/6Nxc-3WpMbg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'A Separation',
                'slug' => Str::slug('A Separation'),
                'description' => 'A married couple are faced with a difficult decision - to improve the life of their child by moving to another country or to stay in Iran and look after a deteriorating parent who has Alzheimer\'s disease.',
                'director' => 'Asghar Farhadi',
                'writers' => 'Asghar Farhadi',
                'stars' => 'Payman Maadi, Leila Hatami, Sareh Bayat',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BN2JmMjViMjMtZTM5Mi00ZGZkLTk5YzctZDg5MjFjZDE4NjNkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2011-03-16',
                'duration' => 123,
                'url_720' => 'https://www.youtube.com/embed/58Onuy5USTc',
                'url_1080' => 'https://www.youtube.com/embed/1K2jkbCZR2I',
                'url_4k' => 'https://www.youtube.com/embed/6ZBi3lQU5lw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Incendies',
                'slug' => Str::slug('Incendies'),
                'description' => 'Twins journey to the Middle East to discover their family history and fulfill their mother\'s last wishes.',
                'director' => 'Denis Villeneuve',
                'writers' => 'Denis Villeneuve (screenplay), Wajdi Mouawad (play)',
                'stars' => 'Lubna Azabal, Mélissa Désormeaux-Poulin, Maxim Gaudette',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMWE3MGYzZjktY2Q5Mi00Y2NiLWIyYWUtMmIyNzA3YmZlMGFhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2010-09-04',
                'duration' => 131,
                'url_720' => 'https://www.youtube.com/embed/9XaX4W9qR3A',
                'url_1080' => 'https://www.youtube.com/embed/00Z6aJN6UrY',
                'url_4k' => 'https://www.youtube.com/embed/3YJn5dYVSWk',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Secret in Their Eyes',
                'slug' => Str::slug('The Secret in Their Eyes'),
                'description' => 'A retired legal counselor writes a novel hoping to find closure for one of his past unresolved homicide cases and for his unreciprocated love with his superior - both of which still haunt him decades later.',
                'director' => 'Juan José Campanella',
                'writers' => 'Eduardo Sacheri (novel), Juan José Campanella (screenplay)',
                'stars' => 'Ricardo Darín, Soledad Villamil, Pablo Rago',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTgwNTI3OTczOV5BMl5BanBnXkFtZTcwMTM3MTUyMw@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2009-08-13',
                'duration' => 129,
                'url_720' => 'https://www.youtube.com/embed/7H6T7FS3F-Y',
                'url_1080' => 'https://www.youtube.com/embed/9oQK8ZCTM3A',
                'url_4k' => 'https://www.youtube.com/embed/1QZ3yQ3z3JY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'City of God',
                'slug' => Str::slug('City of God'),
                'description' => 'In the slums of Rio, two kids\' paths diverge as one struggles to become a photographer and the other a kingpin.',
                'director' => 'Fernando Meirelles, Kátia Lund',
                'writers' => 'Paulo Lins (novel), Bráulio Mantovani (screenplay)',
                'stars' => 'Alexandre Rodrigues, Leandro Firmino, Matheus Nachtergaele',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMGU5OWEwZDItNmNkMC00NzZmLTk1YTctNzVhZTJjM2NlZTVmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2002-08-30',
                'duration' => 130,
                'url_720' => 'https://www.youtube.com/embed/dcUOO4Itgmw',
                'url_1080' => 'https://www.youtube.com/embed/ioUE_5wpg_E',
                'url_4k' => 'https://www.youtube.com/embed/CR6H9gqX4Iw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pan\'s Labyrinth',
                'slug' => Str::slug('Pan\'s Labyrinth'),
                'description' => 'In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.',
                'director' => 'Guillermo del Toro',
                'writers' => 'Guillermo del Toro',
                'stars' => 'Ivana Baquero, Ariadna Gil, Sergi López',
                'poster' => 'https://image.tmdb.org/t/p/w500/qG3RYlIVpTYclR9TYIsy8p7m7AT.jpg',
                'release_date' => '2006-10-11',
                'duration' => 118,
                'url_720' => 'https://www.youtube.com/embed/E7XGNPXdlGQ',
                'url_1080' => 'https://www.youtube.com/embed/4Evbx9QF0R4',
                'url_4k' => 'https://www.youtube.com/embed/5YQY8a0R7kY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Amadeus',
                'slug' => Str::slug('Amadeus'),
                'description' => 'The life, success and troubles of Wolfgang Amadeus Mozart, as told by Antonio Salieri, the contemporaneous composer who was insanely jealous of Mozart\'s talent and claimed to have murdered him.',
                'director' => 'Milos Forman',
                'writers' => 'Peter Shaffer (original stage play), Peter Shaffer (screenplay)',
                'stars' => 'F. Murray Abraham, Tom Hulce, Elizabeth Berridge',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNWJlNzUzNGMtYTAwMS00ZjI2LWFmNWQtODcxNWUxODA5YmU1XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1984-09-19',
                'duration' => 160,
                'url_720' => 'https://www.youtube.com/embed/r7kWQj9FCGY',
                'url_1080' => 'https://www.youtube.com/embed/yIzhAKtEzY0',
                'url_4k' => 'https://www.youtube.com/embed/7L4q7JvX_oA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Sting',
                'slug' => Str::slug('The Sting'),
                'description' => 'Two grifters team up to pull off the ultimate con.',
                'director' => 'George Roy Hill',
                'writers' => 'David S. Ward',
                'stars' => 'Paul Newman, Robert Redford, Robert Shaw',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNGU3NjQ4YTMtZGJjOS00YTQ3LThmNmItMTI5MDE2ODI3NzY3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1973-12-25',
                'duration' => 129,
                'url_720' => 'https://www.youtube.com/embed/Lm8p5rlrSkY',
                'url_1080' => 'https://www.youtube.com/embed/35BngQKcxDM',
                'url_4k' => 'https://www.youtube.com/embed/qqB9SGVN_4A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Once Upon a Time in the West',
                'slug' => Str::slug('Once Upon a Time in the West'),
                'description' => 'A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.',
                'director' => 'Sergio Leone',
                'writers' => 'Sergio Donati (screenplay), Sergio Leone (screenplay)',
                'stars' => 'Henry Fonda, Charles Bronson, Claudia Cardinale',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BODQ3NDExOGYtMzI3Mi00NWRlLTkwNjAtNjc4MDgzZGJiZTA1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1968-12-21',
                'duration' => 165,
                'url_720' => 'https://www.youtube.com/embed/5G2R5ZP1To8',
                'url_1080' => 'https://www.youtube.com/embed/9QyD7qQ7p5k',
                'url_4k' => 'https://www.youtube.com/embed/9QyD7qQ7p5k',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Apartment',
                'slug' => Str::slug('The Apartment'),
                'description' => 'A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.',
                'director' => 'Billy Wilder',
                'writers' => 'Billy Wilder, I.A.L. Diamond',
                'stars' => 'Jack Lemmon, Shirley MacLaine, Fred MacMurray',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNzkwODFjNzItMmMwNi00MTU5LWE2MzktM2M4ZDczZGM1MmViXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1960-06-15',
                'duration' => 125,
                'url_720' => 'https://www.youtube.com/embed/1bqMY82xzWo',
                'url_1080' => 'https://www.youtube.com/embed/7aJ7hWyeydY',
                'url_4k' => 'https://www.youtube.com/embed/3zWqJZLkl5U',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Some Like It Hot',
                'slug' => Str::slug('Some Like It Hot'),
                'description' => 'After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.',
                'director' => 'Billy Wilder',
                'writers' => 'Billy Wilder (screenplay), I.A.L. Diamond (screenplay)',
                'stars' => 'Marilyn Monroe, Tony Curtis, Jack Lemmon',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNzAyOGIxYjAtMGY2NC00ZTgyLWIwMWEtYzY0OWQ4NDFjOTc5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1959-03-19',
                'duration' => 121,
                'url_720' => 'https://www.youtube.com/embed/rI_lUHOCcbc',
                'url_1080' => 'https://www.youtube.com/embed/wf4lWp8sL1Q',
                'url_4k' => 'https://www.youtube.com/embed/7LjTIQh1cDg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Casablanca',
                'slug' => Str::slug('Casablanca'),
                'description' => 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.',
                'director' => 'Michael Curtiz',
                'writers' => 'Julius J. Epstein (screenplay), Philip G. Epstein (screenplay)',
                'stars' => 'Humphrey Bogart, Ingrid Bergman, Paul Henreid',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1942-11-26',
                'duration' => 102,
                'url_720' => 'https://www.youtube.com/embed/BkL9l7qovsE',
                'url_1080' => 'https://www.youtube.com/embed/EJvlGh_FgcI',
                'url_4k' => 'https://www.youtube.com/embed/1a-6RTZqq5g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gone with the Wind',
                'slug' => Str::slug('Gone with the Wind'),
                'description' => 'A manipulative Southern belle carries on a turbulent affair with a blockade runner during the American Civil War.',
                'director' => 'Victor Fleming',
                'writers' => 'Margaret Mitchell (novel), Sidney Howard (screenplay)',
                'stars' => 'Clark Gable, Vivien Leigh, Thomas Mitchell',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BYjUyZWZkM2UtMzYxYy00ZmQ3LWFmZTQtOGE2YjBkNjA3YWZlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1939-12-15',
                'duration' => 238,
                'url_720' => 'https://www.youtube.com/embed/8mM8iNarcRc',
                'url_1080' => 'https://www.youtube.com/embed/h2E5ODI3jY4',
                'url_4k' => 'https://www.youtube.com/embed/8mM8iNarcRc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Psycho',
                'slug' => Str::slug('Psycho'),
                'description' => 'A Phoenix secretary embezzles $40,000 from her employer\'s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.',
                'director' => 'Alfred Hitchcock',
                'writers' => 'Joseph Stefano (screenplay), Robert Bloch (novel)',
                'stars' => 'Anthony Perkins, Janet Leigh, Vera Miles',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1960-06-16',
                'duration' => 109,
                'url_720' => 'https://www.youtube.com/embed/Wz719b9QUqY',
                'url_1080' => 'https://www.youtube.com/embed/NG3-GlvKPcg',
                'url_4k' => 'https://www.youtube.com/embed/DTJQfFQ40lI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Schindler\'s List',
                'slug' => Str::slug('Schindler\'s List'),
                'description' => 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
                'director' => 'Steven Spielberg',
                'writers' => 'Thomas Keneally (book), Steven Zaillian (screenplay)',
                'stars' => 'Liam Neeson, Ralph Fiennes, Ben Kingsley',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1993-11-30',
                'duration' => 195,
                'url_720' => 'https://www.youtube.com/embed/gG22XNhtnoY',
                'url_1080' => 'https://www.youtube.com/embed/mxphAlJID9U',
                'url_4k' => 'https://www.youtube.com/embed/M6pW6Jj8E0M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Good, the Bad and the Ugly',
                'slug' => Str::slug('The Good, the Bad and the Ugly'),
                'description' => 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
                'director' => 'Sergio Leone',
                'writers' => 'Luciano Vincenzoni (story), Sergio Leone (story)',
                'stars' => 'Clint Eastwood, Eli Wallach, Lee Van Cleef',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1966-12-23',
                'duration' => 178,
                'url_720' => 'https://www.youtube.com/embed/WCN5JJY_wiA',
                'url_1080' => 'https://www.youtube.com/embed/IFNUGzCOQoI',
                'url_4k' => 'https://www.youtube.com/embed/pS4Z-OeW7n0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '12 Angry Men',
                'slug' => Str::slug('12 Angry Men'),
                'description' => 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.',
                'director' => 'Sidney Lumet',
                'writers' => 'Reginald Rose (story), Reginald Rose (screenplay)',
                'stars' => 'Henry Fonda, Lee J. Cobb, Martin Balsam',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1957-04-10',
                'duration' => 96,
                'url_720' => 'https://www.youtube.com/embed/_13J_9B5jEk',
                'url_1080' => 'https://www.youtube.com/embed/TEN-2uTi2c0',
                'url_4k' => 'https://www.youtube.com/embed/7DkI2H4Hf_c',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lord of the Rings: The Return of the King',
                'slug' => Str::slug('The Lord of the Rings: The Return of the King'),
                'description' => 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
                'director' => 'Peter Jackson',
                'writers' => 'J.R.R. Tolkien (novel), Fran Walsh (screenplay)',
                'stars' => 'Elijah Wood, Viggo Mortensen, Ian McKellen',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2003-12-17',
                'duration' => 201,
                'url_720' => 'https://www.youtube.com/embed/r5X-hFf6Bwo',
                'url_1080' => 'https://www.youtube.com/embed/y2rYRu8UW8M',
                'url_4k' => 'https://www.youtube.com/embed/zckJCxYxn1g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pulp Fiction',
                'slug' => Str::slug('Pulp Fiction'),
                'description' => 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
                'director' => 'Quentin Tarantino',
                'writers' => 'Quentin Tarantino (story), Roger Avary (story)',
                'stars' => 'John Travolta, Uma Thurman, Samuel L. Jackson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1994-10-14',
                'duration' => 154,
                'url_720' => 'https://www.youtube.com/embed/s7EdQ4FqbhY',
                'url_1080' => 'https://www.youtube.com/embed/tGpTpVyI_OQ',
                'url_4k' => 'https://www.youtube.com/embed/5ZAhzsi1ybM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lord of the Rings: The Two Towers',
                'slug' => Str::slug('The Lord of the Rings: The Two Towers'),
                'description' => 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron\'s new ally, Saruman, and his hordes of Isengard.',
                'director' => 'Peter Jackson',
                'writers' => 'J.R.R. Tolkien (novel), Fran Walsh (screenplay)',
                'stars' => 'Elijah Wood, Ian McKellen, Viggo Mortensen',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2002-12-18',
                'duration' => 179,
                'url_720' => 'https://www.youtube.com/embed/hYcw5ksV8YQ',
                'url_1080' => 'https://www.youtube.com/embed/LbfMDwc4azU',
                'url_4k' => 'https://www.youtube.com/embed/K3WYqPRdKd4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Seven Samurai',
                'slug' => Str::slug('Seven Samurai'),
                'description' => 'Farmers from a village exploited by bandits hire a veteran samurai for protection, who gathers six other samurai to join him.',
                'director' => 'Akira Kurosawa',
                'writers' => 'Akira Kurosawa (screenplay), Shinobu Hashimoto (screenplay)',
                'stars' => 'Toshirô Mifune, Takashi Shimura, Keiko Tsushima',
                'poster' => 'https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
                'release_date' => '1954-04-26',
                'duration' => 207,
                'url_720' => 'https://www.youtube.com/embed/wJ1TOratCTo',
                'url_1080' => 'https://www.youtube.com/embed/3l0qgXjLJ2g',
                'url_4k' => 'https://www.youtube.com/embed/3l0qgXjLJ2g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'It\'s a Wonderful Life',
                'slug' => Str::slug('It\'s a Wonderful Life'),
                'description' => 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.',
                'director' => 'Frank Capra',
                'writers' => 'Frances Goodrich (screenplay), Albert Hackett (screenplay)',
                'stars' => 'James Stewart, Donna Reed, Lionel Barrymore',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1946-12-20',
                'duration' => 130,
                'url_720' => 'https://www.youtube.com/embed/iLR3gZrU2Xo',
                'url_1080' => 'https://www.youtube.com/embed/LJfZaT8ncYk',
                'url_4k' => 'https://www.youtube.com/embed/1M4FGAB4uZU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Good Will Hunting',
                'slug' => Str::slug('Good Will Hunting'),
                'description' => 'Will Hunting, a janitor at M.I.T., has a gift for mathematics but needs help from a psychologist to find direction in his life.',
                'director' => 'Gus Van Sant',
                'writers' => 'Matt Damon (screenplay), Ben Affleck (screenplay)',
                'stars' => 'Robin Williams, Matt Damon, Ben Affleck',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1997-12-05',
                'duration' => 126,
                'url_720' => 'https://www.youtube.com/embed/PaZVjZEFkRs',
                'url_1080' => 'https://www.youtube.com/embed/QSMvyuEeIyw',
                'url_4k' => 'https://www.youtube.com/embed/Hm3JodBR-vs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('movies')->insert($movies);

        Schema::enableForeignKeyConstraints();
    }
}
