<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('movies')->truncate();

        $movies = 
        [
            [
                'title' => 'The Shawshank Redemption',
                'slug' => Str::slug('The Shawshank Redemption'),
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'director' => 'Frank Darabont',
                'writers' => 'Stephen King (short story "Rita Hayworth and Shawshank Redemption"), Frank Darabont (screenplay)',
                'stars' => 'Tim Robbins, Morgan Freeman, Bob Gunton',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1994-09-23',
                'duration' => 142,
                'url_720' => 'https://www.youtube.com/embed/6hB3S9bIaco',
                'url_1080' => 'https://www.youtube.com/embed/PLl99DlL6b4',
                'url_4k' => 'https://www.youtube.com/embed/NmzuHjWmXOc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Godfather',
                'slug' => Str::slug('The Godfather'),
                'description' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
                'director' => 'Francis Ford Coppola',
                'writers' => 'Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by)',
                'stars' => 'Marlon Brando, Al Pacino, James Caan',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1972-03-24',
                'duration' => 175,
                'url_720' => 'https://www.youtube.com/embed/sY1S34973zA',
                'url_1080' => 'https://www.youtube.com/embed/UaVTIH8mujA',
                'url_4k' => 'https://www.youtube.com/embed/1x0GpEZnwa8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Dark Knight',
                'slug' => Str::slug('The Dark Knight'),
                'description' => 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay)',
                'stars' => 'Christian Bale, Heath Ledger, Aaron Eckhart',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2008-07-18',
                'duration' => 152,
                'url_720' => 'https://www.youtube.com/embed/EXeTwQWrcwY',
                'url_1080' => 'https://www.youtube.com/embed/LDG9bisJEaI',
                'url_4k' => 'https://www.youtube.com/embed/8gqM4BCgG8Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pulp Fiction',
                'slug' => Str::slug('Pulp Fiction'),
                'description' => 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
                'director' => 'Quentin Tarantino',
                'writers' => 'Quentin Tarantino (story), Roger Avary (story)',
                'stars' => 'John Travolta, Uma Thurman, Samuel L. Jackson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1994-10-14',
                'duration' => 154,
                'url_720' => 'https://www.youtube.com/embed/s7EdQ4FqbhY',
                'url_1080' => 'https://www.youtube.com/embed/tGpTpVyI_OQ',
                'url_4k' => 'https://www.youtube.com/embed/5ZAhzsi1ybM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Forrest Gump',
                'slug' => Str::slug('Forrest Gump'),
                'description' => 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
                'director' => 'Robert Zemeckis',
                'writers' => 'Winston Groom (novel), Eric Roth (screenplay)',
                'stars' => 'Tom Hanks, Robin Wright, Gary Sinise',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1994-07-06',
                'duration' => 142,
                'url_720' => 'https://www.youtube.com/embed/bLvqoHBptjg',
                'url_1080' => 'https://www.youtube.com/embed/uPIEn0M8su0',
                'url_4k' => 'https://www.youtube.com/embed/XHhAG-YLdk8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inception',
                'slug' => Str::slug('Inception'),
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'director' => 'Christopher Nolan',
                'writers' => 'Christopher Nolan',
                'stars' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2010-07-16',
                'duration' => 148,
                'url_720' => 'https://www.youtube.com/embed/YoHD9XEInc0',
                'url_1080' => 'https://www.youtube.com/embed/8hP9D6kZseM',
                'url_4k' => 'https://www.youtube.com/embed/HcoZbHBDHQA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fight Club',
                'slug' => Str::slug('Fight Club'),
                'description' => 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
                'director' => 'David Fincher',
                'writers' => 'Chuck Palahniuk (novel), Jim Uhls (screenplay)',
                'stars' => 'Brad Pitt, Edward Norton, Helena Bonham Carter',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1999-10-15',
                'duration' => 139,
                'url_720' => 'https://www.youtube.com/embed/qtRKdVHc-cE',
                'url_1080' => 'https://www.youtube.com/embed/BdJKm16Co6M',
                'url_4k' => 'https://www.youtube.com/embed/O1nDozs-LxI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Matrix',
                'slug' => Str::slug('The Matrix'),
                'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
                'director' => 'Lana Wachowski, Lilly Wachowski',
                'writers' => 'Lana Wachowski, Lilly Wachowski',
                'stars' => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1999-03-31',
                'duration' => 136,
                'url_720' => 'https://www.youtube.com/embed/vKQi3bBA1y8',
                'url_1080' => 'https://www.youtube.com/embed/m8e-FF8MsqU',
                'url_4k' => 'https://www.youtube.com/embed/9ix7TUGVYIo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Goodfellas',
                'slug' => Str::slug('Goodfellas'),
                'description' => 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
                'director' => 'Martin Scorsese',
                'writers' => 'Nicholas Pileggi (book), Martin Scorsese (screenplay)',
                'stars' => 'Robert De Niro, Ray Liotta, Joe Pesci',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1990-09-19',
                'duration' => 146,
                'url_720' => 'https://www.youtube.com/embed/2ilzidi_J8Q',
                'url_1080' => 'https://www.youtube.com/embed/qo5jJpHtI1Y',
                'url_4k' => 'https://www.youtube.com/embed/WHXxVmeGQUc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Silence of the Lambs',
                'slug' => Str::slug('The Silence of the Lambs'),
                'description' => 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
                'director' => 'Jonathan Demme',
                'writers' => 'Thomas Harris (novel), Ted Tally (screenplay)',
                'stars' => 'Jodie Foster, Anthony Hopkins, Scott Glenn',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1991-02-14',
                'duration' => 118,
                'url_720' => 'https://www.youtube.com/embed/W6Mm8Sbe__o',
                'url_1080' => 'https://www.youtube.com/embed/RuX2MQeb8UM',
                'url_4k' => 'https://www.youtube.com/embed/8Qsq6DrYDxE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Interstellar',
                'slug' => Str::slug('Interstellar'),
                'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan, Christopher Nolan',
                'stars' => 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2014-11-07',
                'duration' => 169,
                'url_720' => 'https://www.youtube.com/embed/zSWdZVtXT7E',
                'url_1080' => 'https://www.youtube.com/embed/0vxOhd4qlnA',
                'url_4k' => 'https://www.youtube.com/embed/2LqzF5WauAw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lord of the Rings: The Fellowship of the Ring',
                'slug' => Str::slug('The Lord of the Rings: The Fellowship of the Ring'),
                'description' => 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
                'director' => 'Peter Jackson',
                'writers' => 'J.R.R. Tolkien (novel), Fran Walsh (screenplay)',
                'stars' => 'Elijah Wood, Ian McKellen, Viggo Mortensen',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2001-12-19',
                'duration' => 178,
                'url_720' => 'https://www.youtube.com/embed/V75dMMIW2B4',
                'url_1080' => 'https://www.youtube.com/embed/_e8QGuG50ro',
                'url_4k' => 'https://www.youtube.com/embed/uYnQDsaxHZU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Parasite',
                'slug' => Str::slug('Parasite'),
                'description' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
                'director' => 'Bong Joon Ho',
                'writers' => 'Bong Joon Ho (story), Han Jin Won (screenplay)',
                'stars' => 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2019-05-21',
                'duration' => 132,
                'url_720' => 'https://www.youtube.com/embed/SEUXfv87Wpk',
                'url_1080' => 'https://www.youtube.com/embed/5xH0HfJHsaY',
                'url_4k' => 'https://www.youtube.com/embed/PhPROeYAYBA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Whiplash',
                'slug' => Str::slug('Whiplash'),
                'description' => 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
                'director' => 'Damien Chazelle',
                'writers' => 'Damien Chazelle',
                'stars' => 'Miles Teller, J.K. Simmons, Melissa Benoist',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2014-10-10',
                'duration' => 106,
                'url_720' => 'https://www.youtube.com/embed/7d_jQycdQGo',
                'url_1080' => 'https://www.youtube.com/embed/ZZY-Ytrw2co',
                'url_4k' => 'https://www.youtube.com/embed/teHfyby_veU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Green Mile',
                'slug' => Str::slug('The Green Mile'),
                'description' => 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
                'director' => 'Frank Darabont',
                'writers' => 'Stephen King (novel), Frank Darabont (screenplay)',
                'stars' => 'Tom Hanks, Michael Clarke Duncan, David Morse',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1999-12-10',
                'duration' => 189,
                'url_720' => 'https://www.youtube.com/embed/Ki4haFrqSrw',
                'url_1080' => 'https://www.youtube.com/embed/Bg7epsq0OIQ',
                'url_4k' => 'https://www.youtube.com/embed/ctRK-4Vt7dA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Departed',
                'slug' => Str::slug('The Departed'),
                'description' => 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
                'director' => 'Martin Scorsese',
                'writers' => 'Alan Mak (film), Felix Chong (film)',
                'stars' => 'Leonardo DiCaprio, Matt Damon, Jack Nicholson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2006-10-06',
                'duration' => 151,
                'url_720' => 'https://www.youtube.com/embed/iojhqm0JTW4',
                'url_1080' => 'https://www.youtube.com/embed/auYbpnEwBBg',
                'url_4k' => 'https://www.youtube.com/embed/SGWvwjZ0eDc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gladiator',
                'slug' => Str::slug('Gladiator'),
                'description' => 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
                'director' => 'Ridley Scott',
                'writers' => 'David Franzoni (story), John Logan (screenplay)',
                'stars' => 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2000-05-05',
                'duration' => 155,
                'url_720' => 'https://www.youtube.com/embed/owK1qxDselE',
                'url_1080' => 'https://www.youtube.com/embed/P5ieIbInFpg',
                'url_4k' => 'https://www.youtube.com/embed/b_VKnQfZX4c',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Prestige',
                'slug' => Str::slug('The Prestige'),
                'description' => 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay)',
                'stars' => 'Christian Bale, Hugh Jackman, Scarlett Johansson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2006-10-20',
                'duration' => 130,
                'url_720' => 'https://www.youtube.com/embed/o4gHCmTQDVI',
                'url_1080' => 'https://www.youtube.com/embed/RLtaA9fFNXU',
                'url_4k' => 'https://www.youtube.com/embed/ijXruSzfGEc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Django Unchained',
                'slug' => Str::slug('Django Unchained'),
                'description' => 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
                'director' => 'Quentin Tarantino',
                'writers' => 'Quentin Tarantino',
                'stars' => 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2012-12-25',
                'duration' => 165,
                'url_720' => 'https://www.youtube.com/embed/0fUCuvNlOCg',
                'url_1080' => 'https://www.youtube.com/embed/_iH0UBYDI4g',
                'url_4k' => 'https://www.youtube.com/embed/eUdM9vrCbow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Social Network',
                'slug' => Str::slug('The Social Network'),
                'description' => 'As Harvard student Mark Zuckerberg creates the social networking site that would become Facebook, he is sued by the twins who claimed he stole their idea.',
                'director' => 'David Fincher',
                'writers' => 'Aaron Sorkin (screenplay), Ben Mezrich (book)',
                'stars' => 'Jesse Eisenberg, Andrew Garfield, Justin Timberlake',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2010-10-01',
                'duration' => 120,
                'url_720' => 'https://www.youtube.com/embed/lB95KLmpLR4',
                'url_1080' => 'https://www.youtube.com/embed/8N4TMvz6XwQ',
                'url_4k' => 'https://www.youtube.com/embed/2RB3edZyeYw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inglourious Basterds',
                'slug' => Str::slug('Inglourious Basterds'),
                'description' => 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans.',
                'director' => 'Quentin Tarantino',
                'writers' => 'Quentin Tarantino',
                'stars' => 'Brad Pitt, Christoph Waltz, Mélanie Laurent',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2009-08-21',
                'duration' => 153,
                'url_720' => 'https://www.youtube.com/embed/KnrRy6kSFF0',
                'url_1080' => 'https://www.youtube.com/embed/qRYgNqnqBdY',
                'url_4k' => 'https://www.youtube.com/embed/6AtLlVNsuAc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Grand Budapest Hotel',
                'slug' => Str::slug('The Grand Budapest Hotel'),
                'description' => 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
                'director' => 'Wes Anderson',
                'writers' => 'Wes Anderson (screenplay), Hugo Guinness (story)',
                'stars' => 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2014-03-28',
                'duration' => 99,
                'url_720' => 'https://www.youtube.com/embed/1Fg5iWmQjwk',
                'url_1080' => 'https://www.youtube.com/embed/zru-1DbbcsA',
                'url_4k' => 'https://www.youtube.com/embed/eTdf-nHhPWM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'La La Land',
                'slug' => Str::slug('La La Land'),
                'description' => 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
                'director' => 'Damien Chazelle',
                'writers' => 'Damien Chazelle',
                'stars' => 'Ryan Gosling, Emma Stone, John Legend',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2016-12-09',
                'duration' => 128,
                'url_720' => 'https://www.youtube.com/embed/0pdqf4P9MB8',
                'url_1080' => 'https://www.youtube.com/embed/45TbOYFZ0Lk',
                'url_4k' => 'https://www.youtube.com/embed/je0aAf2f8XQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mad Max: Fury Road',
                'slug' => Str::slug('Mad Max: Fury Road'),
                'description' => 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
                'director' => 'George Miller',
                'writers' => 'George Miller, Brendan McCarthy',
                'stars' => 'Tom Hardy, Charlize Theron, Nicholas Hoult',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2015-05-15',
                'duration' => 120,
                'url_720' => 'https://www.youtube.com/embed/hEJnMQG9ev8',
                'url_1080' => 'https://www.youtube.com/embed/YWNWi-ZWL3c',
                'url_4k' => 'https://www.youtube.com/embed/cdLl1GVjOrc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Shining',
                'slug' => Str::slug('The Shining'),
                'description' => 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.',
                'director' => 'Stanley Kubrick',
                'writers' => 'Stephen King (novel), Stanley Kubrick (screenplay)',
                'stars' => 'Jack Nicholson, Shelley Duvall, Danny Lloyd',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1980-05-23',
                'duration' => 146,
                'url_720' => 'https://www.youtube.com/embed/S014oGZiSdI',
                'url_1080' => 'https://www.youtube.com/embed/5Cb3ik6zP2I',
                'url_4k' => 'https://www.youtube.com/embed/FZQvIJxG9Xs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Se7en',
                'slug' => Str::slug('Se7en'),
                'description' => 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
                'director' => 'David Fincher',
                'writers' => 'Andrew Kevin Walker',
                'stars' => 'Morgan Freeman, Brad Pitt, Kevin Spacey',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1995-09-22',
                'duration' => 127,
                'url_720' => 'https://www.youtube.com/embed/znmZoVkCjpI',
                'url_1080' => 'https://www.youtube.com/embed/SpKbZ_3zlb0',
                'url_4k' => 'https://www.youtube.com/embed/J4YV2_TcCoE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lion King',
                'slug' => Str::slug('The Lion King'),
                'description' => 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
                'director' => 'Roger Allers, Rob Minkoff',
                'writers' => 'Irene Mecchi (screenplay), Jonathan Roberts (screenplay)',
                'stars' => 'Matthew Broderick, Jeremy Irons, James Earl Jones',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1994-06-24',
                'duration' => 88,
                'url_720' => 'https://www.youtube.com/embed/4sj1MT05lAA',
                'url_1080' => 'https://www.youtube.com/embed/eHcZlPpNt0Q',
                'url_4k' => 'https://www.youtube.com/embed/GibiNy4d4gc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Back to the Future',
                'slug' => Str::slug('Back to the Future'),
                'description' => 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.',
                'director' => 'Robert Zemeckis',
                'writers' => 'Robert Zemeckis, Bob Gale',
                'stars' => 'Michael J. Fox, Christopher Lloyd, Lea Thompson',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1985-07-03',
                'duration' => 116,
                'url_720' => 'https://www.youtube.com/embed/qvsgGtivCgs',
                'url_1080' => 'https://www.youtube.com/embed/yosuvf7Unmg',
                'url_4k' => 'https://www.youtube.com/embed/7D7xWXEnW-4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Alien',
                'slug' => Str::slug('Alien'),
                'description' => 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.',
                'director' => 'Ridley Scott',
                'writers' => 'Dan O\'Bannon (screenplay), Ronald Shusett (story)',
                'stars' => 'Sigourney Weaver, Tom Skerritt, John Hurt',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1979-06-22',
                'duration' => 117,
                'url_720' => 'https://www.youtube.com/embed/LjLamj-b0I8',
                'url_1080' => 'https://www.youtube.com/embed/3mKPrxjwF7A',
                'url_4k' => 'https://www.youtube.com/embed/7bhWjnJgX8E',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Joker',
                'slug' => Str::slug('Joker'),
                'description' => 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
                'director' => 'Todd Phillips',
                'writers' => 'Todd Phillips (screenplay), Scott Silver (screenplay)',
                'stars' => 'Joaquin Phoenix, Robert De Niro, Zazie Beetz',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2019-10-04',
                'duration' => 122,
                'url_720' => 'https://www.youtube.com/embed/zAGVQLHvwOY',
                'url_1080' => 'https://www.youtube.com/embed/t433PEQGErc',
                'url_4k' => 'https://www.youtube.com/embed/rgXplohCw5o',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Terminator',
                'slug' => Str::slug('The Terminator'),
                'description' => 'A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity\'s future salvation.',
                'director' => 'James Cameron',
                'writers' => 'James Cameron, Gale Anne Hurd',
                'stars' => 'Arnold Schwarzenegger, Linda Hamilton, Michael Biehn',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '1984-10-26',
                'duration' => 107,
                'url_720' => 'https://www.youtube.com/embed/k64P4l2Wmeg',
                'url_1080' => 'https://www.youtube.com/embed/c4Jo8QoOTQ4',
                'url_4k' => 'https://www.youtube.com/embed/7QXDPzx71jQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blade Runner 2049',
                'slug' => Str::slug('Blade Runner 2049'),
                'description' => 'A young blade runner\'s discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who\'s been missing for thirty years.',
                'director' => 'Denis Villeneuve',
                'writers' => 'Hampton Fancher (screenplay), Michael Green (screenplay)',
                'stars' => 'Ryan Gosling, Harrison Ford, Ana de Armas',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_FMjpg_UX1000_.jpg',
                'release_date' => '2017-10-06',
                'duration' => 164,
                'url_720' => 'https://www.youtube.com/embed/gCcx85zbxz4',
                'url_1080' => 'https://www.youtube.com/embed/dZOaI_Fn5o4',
                'url_4k' => 'https://www.youtube.com/embed/8ixEWrTLiQ4',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('movies')->insert($movies);

        Schema::enableForeignKeyConstraints();
    }
}
